language: swift
osx_image: xcode10.2
env:
  global:
  - WORKSPACE=EnumeratedTable.xcworkspace
  - FRAMEWORK_NAME=EnumeratedTable
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6"
    - DESTINATION="OS=10.3,name=iPhone 7"
    - DESTINATION="OS=11.4,name=iPhone X"
    - DESTINATION="OS=12.2,name=iPhone XS"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_NAME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;