language: swift
osx_image: xcode10.3
xcode_project: EnumeratedTable.xcodeproj
xcode_scheme: EnumeratedTable
xcode_sdk: iphonesimulator12.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=EnumeratedTable.xcworkspace
  - FRAMEWORK_NAME=EnumeratedTable