language: swift
osx_image: xcode10.2
env:
  global:
  - WORKSPACE=EnumeratedTable.xcworkspace
  - FRAMEWORK_NAME=EnumeratedTable
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6" SCHEME:"$FRAMEWORK_NAME"
    - DESTINATION="OS=10.3,name=iPhone 7" SCHEME:"$FRAMEWORK_NAME"
    - DESTINATION="OS=11.4,name=iPhone X" SCHEME:"$FRAMEWORK_NAME"
    - DESTINATION="OS=12.2,name=iPhone XS" SCHEME:"$FRAMEWORK_NAME"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;